package_assets: on
package_path: assets-compiled
compress_assets: true
javascript_compressor: closure
gzip_assets: true

javascripts:
  common:
    - public/javascripts/**/*.js

stylesheets:
  common:
    - public/stylesheets/**/*.css
